name: Publish Hot Fix

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: CDP-build-hotfix-workflow
    runs-on: ubuntu-latest
    permissions:
      contents: write # Create the release tag.
      id-token: write # Authenticate to AWS using OIDC.
    env:
      AWS_REGION: eu-west-2
      AWS_ACCOUNT_ID: "094954420758"
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0 # Depth 0 required for branch-based versioning
      - name: Publish Hot Fix
        uses: DEFRA/cdp-build-action/build-hotfix@dfb527d1bca7591fbbfd32ac007557745e888cf2 # main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
