name: Run SonarCloud coverage scan

on:
  workflow_call:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  SONAR_SCANNER_VERSION: 11.3.0
  DOTNET_COVERAGE_VERSION: 18.11.2

jobs:
  build:
    if: github.run_number != 1
    name: CDP SonarCloud coverage scan
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4
        with:
          java-version: 17
          distribution: "zulu"
      - name: Check out code
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5
        with:
          fetch-depth: 0
      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5
        with:
          dotnet-version: |
            10.0
      - name: Cache SonarCloud packages
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: ~/sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner-${{ env.SONAR_SCANNER_VERSION }}
      - name: Cache dotNet code coverage
        id: cache-sonar-coverage
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: ./.sonar/coverage
          key: ${{ runner.os }}-sonar-coverage-${{ env.DOTNET_COVERAGE_VERSION }}
      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./.sonar/scanner
          dotnet tool install dotnet-sonarscanner --version "$SONAR_SCANNER_VERSION" --tool-path ./.sonar/scanner
      - name: Install dotNet code coverage
        if: steps.cache-sonar-coverage.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./.sonar/coverage
          dotnet tool install dotnet-coverage --version "$DOTNET_COVERAGE_VERSION" --tool-path ./.sonar/coverage
      - name: Build and analyze
        if: github.actor != 'dependabot[bot]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin /k:"DEFRA_cdp-dotnet-backend-template" /o:"defra" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
          dotnet build --no-incremental
          ./.sonar/coverage/dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"
          ./.sonar/scanner/dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
